### ISSUE TITLE
怎么去运行

### ISSUE THREAD

**Issue by YUHAN-GUO** [Ysj001/StablePlugin#1]
大佬好，我该怎么去运行这个项目
hasPlugin 什么情况下会是true呢？
![image](https://github.com/user-attachments/assets/3c66a25b-29ae-4778-861e-ef15d579b0d0)

**Comment by Ysj001** [comment]
> 大佬好，我该怎么去运行这个项目 hasPlugin 什么情况下会是true呢？ ![image](https://private-user-images.githubusercontent.com/43516357/389177329-3c66a25b-29ae-4778-861e-ef15d579b0d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MDgyMTQsIm5iZiI6MTczMjUwNzkxNCwicGF0aCI6Ii80MzUxNjM1Ny8zODkxNzczMjktM2M2NmEyNWItMjlhZS00Nzc4LTg2MWUtZWYxNWQ1NzliMGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDA0MTE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzZDQwMWQzNWY2YmM5NWYxYzFmMTliNmUyZGM1ZTNhZWU3YmQxOGE3MGU0MDg2MzU0NjJhNzRjOTMwOTkwMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.swKWphsAcWHu4Ep3oHStbSNKZhzAKaa4QOaeLSPpD04)

需要先执行 `gradlew publishAllPublicationsToLocalRepository` 将插件编译成本地依赖后再 sync。
另外目前项目还在测试阶段，暂无 README，可以先看源码尝试或关注后续更新。
